

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: t49-server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
spec:
  tls:
  - hosts:
    - api49.my-points.ru
    - web49.my-points.ru
    - insights49.my-points.ru
    secretName: serverpod-tls-t49
  rules:
  - host: "api49.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t49-server-service
            port:
              name: api
  - host: "web49.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t49-server-service
            port:
              name: web
  - host: "insights49.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t49-server-service
            port:
              name: insights
    